// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'API_KEY',
    appId: '1:668995412691:web:3fc25c0305a6c063bfea26',
    messagingSenderId: '668995412691',
    projectId: 'chatapp-46cac',
    authDomain: 'chatapp-46cac.firebaseapp.com',
    storageBucket: 'chatapp-46cac.appspot.com',
    measurementId: 'G-6DR9QXMQCE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'API_KEY',
    appId: '1:668995412691:android:750ace1915a4eb79bfea26',
    messagingSenderId: '668995412691',
    projectId: 'chatapp-46cac',
    storageBucket: 'chatapp-46cac.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'API_KEY',
    appId: '1:668995412691:ios:8d2a89052fb57edcbfea26',
    messagingSenderId: '668995412691',
    projectId: 'chatapp-46cac',
    storageBucket: 'chatapp-46cac.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'API_KEY',
    appId: '1:668995412691:ios:8d2a89052fb57edcbfea26',
    messagingSenderId: '668995412691',
    projectId: 'chatapp-46cac',
    storageBucket: 'chatapp-46cac.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'API_KEY',
    appId: '1:668995412691:web:049bbd21c3d84cf5bfea26',
    messagingSenderId: '668995412691',
    projectId: 'chatapp-46cac',
    authDomain: 'chatapp-46cac.firebaseapp.com',
    storageBucket: 'chatapp-46cac.appspot.com',
    measurementId: 'G-KFCW8NJ7QF',
  );
}
